version: '3.5'
services:
  redis:
    image: redis
    ports:
      - 6379:6379

  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
